// <auto-generated />
using ContactsLawler.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactsLawler.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210208005809_Fix")]
    partial class Fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ContactsLawler.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "438 Limp Ave, Los Angeles, CA 90001",
                            Name = "Fred Durst",
                            Note = "Limp Bizkit",
                            Number = 4832982995L
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "6430 Bulb Ave, Bethesda, Maryland 20810",
                            Name = "Misha Mansoor",
                            Note = "Guitar player",
                            Number = 8003400034L
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "618 E 18th St, Carroll, IA 51401",
                            Name = "Lukas Lawler",
                            Note = "Hey, that's me! Not real info though.",
                            Number = 7127924154L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
